### ISSUE TITLE
I can't find tcp listen 

### ISSUE THREAD

**Issue by coderex2522** [WukLab/LITE#12]
{lite/core/lite_core.c line 5764~5767
        addr.sin_addr.s_addr = htonl((((((ip_a << 8) | ip_b) << 8) | ip_c) << 8) | ip_d);
	printk(KERN_ALERT "establish connection to %x to port %d\n",addr.sin_addr.s_addr, port);
	sockfd = sock_create(PF_INET, SOCK_STREAM, IPPROTO_TCP, &excsocket);
	ret = excsocket->ops->connect(excsocket, (struct sockaddr *)&addr, sizeof(addr), 0);
}
where is listen function?

**Comment by shinyehtsai** [comment]
Listen function is in cluster manager code.
https://github.com/WukLab/LITE/blob/master/cluster-manager/lite-cd.c#L780

**Comment by coderex2522** [comment]
thank you!
