### ISSUE TITLE
Userspace program

### ISSUE THREAD

**Issue by bueryg** [WukLab/LITE#7]
There are only three example programs under lite-userspace. So I am confused about how to use these functions to write my own program.Do I need to read the source code and learn about these functions' usage?

**Comment by shinyehtsai** [comment]
Not really. The APIs you could call from userspace basically can be separated into three types

1. rpc style
2. one-sided rdma style
3. management function
For all the usage of rpc style APIs, (including send, receive, and reply), you could see lite-rpc to find the basic use case. It also needs to register and query port, and the example is also provided in lite-rpc.
For all the usage of rdma style APIs, (including write, read, c&s, f&a), you could see lite-write to find the basic use case. alloc_remote_call is also included in lite-write
For management function such as barrier and join, I think you could find the example under three examples. And get_node_id and get_total_node is basically let you know the node_id and total number of nodes.
